name: "CI"
run-name: "CI - ${{ github.event.head_commit.message || format('Triggered by {0}', github.triggering_actor) }}"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    name: "Test action"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the action
        uses: ./ # Uses an action in the root directory
        id: app
        with:
          app_id: "123,456,789"
          private_key: ${{ secrets.PRIVATE_KEY }}
